[package]
name = "that_bass"
version = "0.1.0"
edition = "2021"
authors = ["Magicolo <magicololand@gmail.com>"]

[dependencies]
that_base_derive = { path = "./that_base_derive" }
parking_lot = "0.12.1"

[dev-dependencies]
checkito = "1.3.6"
criterion = "0.4.0"

[workspace]
members = ["that_base_derive"]

[[bench]]
name = "create"
harness = false
