[package]
name = "that_bass"
version = "0.1.0"
edition = "2021"
authors = ["Magicolo <magicololand@gmail.com>"]

[dependencies]
that_base_derive = { path = "./that_base_derive" }
parking_lot = "*"

[dev-dependencies]
checkito = { path = "../checkito" }

[workspace]
members = ["that_base_derive"]