name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install nightly && rustup default nightly && cargo install cargo-audit
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Audit
      run: cargo audit
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install nightly && rustup default nightly && cargo install cargo-audit
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --release --verbose
    - name: Clippy
      run: cargo clippy --release --verbose -- -D warnings
    - name: Audit
      run: cargo audit
  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: rustup install nightly && rustup default nightly && rustup component add miri
    - name: Test
      run: cargo miri test --verbose